config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :games
  resources :players
  resources :matches
  resources :teams
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home_team,
    class_name: "Team",
    foreign_key: "home_team_id"

  belongs_to :away_team,
    class_name: "Team",
    foreign_key: "away_team_id"

  belongs_to :winner_team,
    class_name: "Team",
    foreign_key: "winner_team_id"

  has_many :matches

  validates_length_of :matches, maximum: 3

  validates :home_team, presence: true
  validates :away_team, presence: true

  validate :check_teams_are_not_the_same

  # For pagination.
  paginates_per 10

  def played_game?
    !winner_team_id.nil?
  end

  private

  def check_teams_are_not_the_same
    if home_team_id == away_team_id
      errors.add(:away_team, "can't be the same as home_team")
    end
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :game
  belongs_to :winner_team, class_name: "Team"

  validates :game, presence: true
  validates :score, presence: true

  validates :score,
    format: {
      with: /\A[0-9]-[0-9]\z/i
    }

  validate :validate_number_of_matched_per_game

  private

  # This is BAD. This should be moved to a service/query object
  def validate_number_of_matched_per_game
    return false if game.nil?
    if game.matches.count > 2
      errors.add(:game, "Max number of games allowed is 3")
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :teams

  validates_presence_of :first_name, :last_name,
    :message => "can't be blank"

  validates_uniqueness_of :first_name, scope: :last_name

  paginates_per 10

  def self.all_uniq_players_mapped
    all.uniq.map do |t|
      [t.full_name, t.id]
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_and_belongs_to_many :players
  has_many :users, through: :players

  has_many :home_games,
    class_name: "Game",
    foreign_key: :home_team_id

  has_many :away_games,
    class_name: "Game",
    foreign_key: :away_team_id

  validates_presence_of :name

  validates_length_of :players, maximum: 2

  paginates_per 10

  def self.all_uniq_teams_mapped
    all.uniq.map do |t|
      [t.name, t.id]
    end
  end

  def games
    [home_games + away_games].flatten.uniq
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :players

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @game   = Game.new
    @games  = Game.all.order(created_at: :desc).page params[:page]
    @teams  = Team.all_uniq_teams_mapped
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      flash[:notice] = 'Game was successfully created.'
    else
      flash[:alert] = @game.errors.full_messages.inspect
    end

    redirect_to games_path
  end

  def show
    @game  = Game.find(params[:id])
    @match = Match.new(game: @game)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path, :alert => "Game deleted."
  end

  private

  def game_params
    params.require(:game).permit(:home_team_id, :away_team_id)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @player   = Player.new
    @players  = Player.all.order(created_at: :desc).page params[:page]
  end

  def create
    @player = Player.new(player_params)
    @player.user = current_user

    if @player.save
      flash[:notice] = 'player was successfully created.'
    else
      flash[:alert] = @player.errors.full_messages.inspect
    end

    redirect_to players_path
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to players_path, :alert => "Player deleted."
  end

  private

  def player_params
    params.require(:player).permit(:first_name, :last_name)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @team    = Team.new
    @teams   = Team.all.order(created_at: :desc).page params[:page]
    @players = Player.all_uniq_players_mapped
  end

  def create
    @team = Team.new(team_params)

    @team.players = extract_players

    if @team.save
      flash[:notice] = 'team was successfully created.'
    else
      flash[:alert] = @team.errors.full_messages.inspect
    end

    redirect_to teams_path
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_path, :alert => "Team deleted."
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end

  def extract_players
    players = params[:team][:players]
    no_empty_players = players.reject { |c| c.empty? }
    Player.find(no_empty_players)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div>
  <%= simple_form_for(@game, :html => {:class => 'form-vertical' }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <div class="col-md-6">
        <%= f.input :home_team_id,
              collection: @teams,
              prompt: "Select first team.",
              label: false
        %>
      </div>

      <div class="col-md-6">
        <%= f.input :away_team_id,
              collection: @teams,
              prompt: "Select second team.",
              label: false
        %>
      </div>

      <br/>

    </div>

    <div class="form-actions text-center">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/games/_game.html.erb
<tr>
  <td>
    <%= link_to game.home_team.name, "#" %>
  </td>

  <td>
    <%= link_to game.away_team.name, "#" %>
  </td>

  <td>
    <%= link_to game.winner_team.name, "#" if game.winner_team.present? %>
  </td>

  <td>
    <%= time_ago_in_words(game.created_at) %>
  </td>

  <td>
    <%= time_ago_in_words(game.updated_at) %>
  </td>

  <td class="actions-cell">
    <%= link_to 'Show', game,  :class => "btn btn-sm btn-info static-popup-link" %>
    <%= link_to "X",
          game_path(game),
          method: :delete,
          data: {
            confirm: "Are you sure you want to permanently delete this game?"
          },
          class: "btn btn-sm btn-danger" %>
  </td>
</tr>

app/views/games/index.html.erb
<div class="text-center">
  <%= paginate @games %>
</div>

<div class="well row">
  <div id="entry-form">
    <div id="insert-form">
      <%= render 'form' %>
    </div>
  </div>
</div>

<hr>

<table class="table table-striped">

    <tr>
      <th>Home Team</th>
      <th>Away Team</th>
      <th>Winner Team</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
    </tr>

    <%= render @games %>

</table>

<br>

<div class="text-center">
  <%= paginate @games %>
</div>

app/views/games/show.html.erb
<table class="table table-striped">
  <tr>
    <th>Home Team</th>
    <th>Away Team</th>
    <th>Winner Team</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
  </tr>

  <%= render [@game] %>
</table>

<hr/>

<div class="well row">
  <div id="entry-form">
    <div id="insert-form">
      <%= render 'matches/form' %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted text-center">Copyright @Eki</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Games', games_path %></li>
    <li><%= link_to 'Players', players_path %></li>
    <li><%= link_to 'Teams', teams_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', "#" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Roomorama Football" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Roomorama Football" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <body>
        <div class="container">
         <%= render 'layouts/messages' %>
         <%= yield %>
        </div>
      </body>
    </main>
  </body>
</html>

app/views/matches/_form.html.erb
<div>
  <%= simple_form_for(@match, :html => {:class => 'form-vertical' }) do |f| %>

    <div class="form-inputs">
      <%= f.input :score,
            placeholder: "Add the score with the format (home_team-away_team ). Ex: 3-4",
            label: false
      %>
    </div>

    <div class="form-actions text-center">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/players/_form.html.erb
<div>
  <%= simple_form_for(@player, :html => {:class => 'form-vertical' }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <div class="col-md-6">
        <%= f.input :first_name,
              placeholder: "Select first team.",
              label: false
        %>
      </div>

      <div class="col-md-6">
        <%= f.input :last_name,
              placeholder: "Select 2nd team.",
              label: false
        %>
      </div>

      <br/>

    </div>

    <div class="form-actions text-center">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/players/_player.html.erb
<tr>
  <td>
    <%= link_to player.first_name, players_path %>
  </td>

  <td>
    <%= link_to player.last_name, players_path %>
  </td>

  <td>
    <%= link_to player.user.email, user_path(player.user) %>
  </td>

  <td>
    <%= time_ago_in_words(player.created_at) %>
  </td>

  <td>
    <%= time_ago_in_words(player.updated_at) %>
  </td>

  <td class="actions-cell">
    <%= link_to "X",
          player_path(player),
          method: :delete,
          data: {
            confirm: "Are you sure you want to permanently delete this player?"
          },
          class: "btn btn-sm btn-danger" %>
  </td>
</tr>

app/views/players/index.html.erb
<div class="text-center">
  <%= paginate @players %>
</div>

<div class="well row">
  <div id="entry-form">
    <div id="insert-form">
      <%= render 'form' %>
    </div>
  </div>
</div>

<hr>

<table class="table table-striped">

    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Created By</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
    </tr>

    <%= render @players %>

</table>

<br>

<div class="text-center">
  <%= paginate @players %>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<div class="well">
  <h3>Welcome</h3>
  <p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

</div>